export const airportList = {
    "ABQ": "Albuquerque, NM",
    "ATL": "Atlanta, GA",
    "BOI": "Boise, ID",
    "BOS": "Boston, MA",
    "CLT": "Charlotte, NC",
    "DEN": "Denver, CO",
    "DFW": "Dallas, TX",
    "DTW": "Detroit, MI",
    "EWR": "Newark, NJ",
    "HNL": "Honolulu, HI",
    "IAD": "Washington, DC",
    "IAH": "Houston, TX",
    "JFK": "New York City, NY",
    "LAS": "Las Vegas, NV",
    "LAX": "Los Angeles, CA",
    "LGA": "New York City, NY",
    "MCO": "Orlando, FL",
    "MIA": "Miami, FL",
    "MSP": "Minneapolis, MN",
    "ORD": "Chicago, IL",
    "PDX": "Portland, OR",
    "PHL": "Philadelphia, PA",
    "PHX": "Phoenix, AZ",
    "SAN": "San Diego, CA",
    "SEA": "Seattle, WA",
    "SFO": "San Francisco, CA",
    "SLC": "Salt Lake City, UT",
    "TUS": "Tucson, AZ"
}

export const airlineList = {
    "Alaska Airlines": "ASA",
    "American Airlines": "AAL",
    "CommutAir": "UCA",
    "Delta": "DAL",
    "Envoy Air": "ENY",
    "Frontier": "FFT",
    "Hawaiian Airlines": "HAL",
    "Horizon": "ASA",
    "JetBlue": "JBU",
    "Mesa": "ASH",
    "PSA Airlines": "JIA",
    "Republic": "RPA",
    "SkyWest": "SKW",
    "Southwest": "SWA",
    "Spirit": "NKS",
    "Sun Country Airlines": "SCX",
    "United": "UAL"
}